{
 "title": "Pizza Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Factory service requests logging",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"factory\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Database requests logging",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"db\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Unhandled Errors Logging",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"unhandledError\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Http Requests logging",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\", type=\"http\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(pizza_creation_failures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pizza_latency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza latency"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizza_revenue_cents_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "service_latency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Request latency"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "active_users{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(auth_success_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_failure_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Endpoint requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(http_requests_get_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(http_requests_post_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "sum(rate(http_requests_put_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate(http_requests_delete_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}